export enum userrole {
    USER="USER",
    SUPPLIER="SUPPLIER",
    HOCKER="HOCKER",
    DELIVERYBOY="DELIVERYBOY",
    PURCHASEMANAGER="PURCHASEMANAGER",
    DEPO="DEPO",
    MANUFACTUREPLANT="MANUFACTUREPLANT"
}